// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaSalesAPI;

#nullable disable

namespace PizzaSalesAPI.Migrations
{
    [DbContext(typeof(PizzaSalesContext))]
    [Migration("20240812154712_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("PizzaSalesAPI.Models.OrderDetails", b =>
                {
                    b.Property<int>("Order_Details_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pizza_Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Order_Details_Id");

                    b.HasIndex("Order_Id");

                    b.HasIndex("Pizza_Id");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PizzaSalesAPI.Models.Orders", b =>
                {
                    b.Property<int>("Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Order_Id");

                    b.HasIndex("Date");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaSalesAPI.Models.Pizza", b =>
                {
                    b.Property<string>("Pizza_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pizza_Type_Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Pizza_Id");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("PizzaSalesAPI.Models.OrderDetails", b =>
                {
                    b.HasOne("PizzaSalesAPI.Models.Orders", "Order")
                        .WithMany("Order_Details")
                        .HasForeignKey("Order_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaSalesAPI.Models.Pizza", "Pizza")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Pizza_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("PizzaSalesAPI.Models.Orders", b =>
                {
                    b.Navigation("Order_Details");
                });

            modelBuilder.Entity("PizzaSalesAPI.Models.Pizza", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
